spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto:
    show-sql:
    properties:
      hibernate:
        format_sql:
      database:
      database-platform:

application:
  security:
    jwt:
      secret-key:
      expiration: